gurk-rs: fix type of env.NIX_LDFLAGS
With ae71a9ea6167 (gurk-rs: prepare for structuredAttrs by moving
OPENSSL_NO_VENDOR into env, 2025-12-19), gurk-rs was prepared to work
with structured attrs. As part of that change, both "NIX_LDFLAGS" and
"OPENSSL_NO_VENDOR" were moved into the `env` attr.

But while the latter conversion is correct, the former is not: when
declared as part of `env` we expect a string, but we still continue to
pass the arguments as an array. This results in the following error:

  error: The `env` attribute set can only contain derivation, string, boolean or integer attributes. The `NIX_LDFLAGS` attribute is of type list.

Fix the issue by using `lib.optionalString` instead.